// src/components/AppointmentForm.js
import React, { useState } from 'react';
import axios from 'axios';

function AppointmentForm() {
  const [ownerName, setOwnerName] = useState('');
  const [autoGeneratedId, setAutoGeneratedId] = useState('');
  const [service, setService] = useState('');
  const [date, setDate] = useState('');
  const [time, setTime] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('http://localhost:3001/api/appointments', {
        owner_name: ownerName,
        auto_generated_id: autoGeneratedId,
        service: service,
        appointment_date: date,
        appointment_time: time,
      });
      alert(`Appointment created: ID = ${response.data.appointmentId}`);
      // Reset form fields
      setOwnerName('');
      setAutoGeneratedId('');
      setService('');
      setDate('');
      setTime('');
    } catch (error) {
      console.error('Error creating appointment:', error);
      alert('Failed to create appointment');
    }
  };

  return (
    <div className =  "AppointmentForm">
    <div style={{ margin: '20px' }}>
      <h2>Make an Appointment</h2>
      <form  className =  "Appointmentbox" onSubmit={handleSubmit}>
        <div>
          <label>Owner's Name: </label>
          <input
            type="text"
            value={ownerName}
            onChange={(e) => setOwnerName(e.target.value)}
            required
          />
        </div>

        <div>
          <label>NIC Number: </label>
          <input
            type="text"
            value={autoGeneratedId}
            onChange={(e) => setAutoGeneratedId(e.target.value)}
            required
          />
        </div>

        <div>
          <label>Service: </label>
          <select
            style={{ width: '100%' }}
            value={service}
            onChange={(e) => setService(e.target.value)}
            required
          >
            <option value="">-- Select a service --</option>
            <option value="Veterinary Services">Veterinary Services</option>
            <option value="Vaccinations">Vaccinations</option>
            <option value="Pet Daycare">Pet Daycare</option>
            <option value="Pet Grooming">Pet Grooming</option>
            <option value="Other">Other</option>
          </select>
        </div>

        <div>
          <label>Appointment Date: </label>
          <input
            type="date"
            value={date}
            onChange={(e) => setDate(e.target.value)}
            required
          />
        </div>

        <div>
          <label>Appointment Time: </label>
          <input
            type="time"
            value={time}
            onChange={(e) => setTime(e.target.value)}
            required
          />
        </div>

        <button type="submit">Submit</button>
      </form>
    </div>
    </div>
  );
}

export default AppointmentForm;
