import React, { useState } from "react";
import axios from "axios";
import { useParams, useNavigate } from "react-router-dom";

function UpdateAppointment() {
  const { id } = useParams();
  const navigate = useNavigate();

  
  const [ownerName, setOwnerName] = useState("");
  const [autoGeneratedId, setAutoGeneratedId] = useState("");
  const [service, setService] = useState("");
  const [date, setDate] = useState("");
  const [time, setTime] = useState("");

  
  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await axios.put(`http://localhost:3001/api/appointments/${id}`, {
        owner_name: ownerName,
        NIC_Number: autoGeneratedId,
        service,
        appointment_date: date,
        appointment_time: time,
      });

      alert("Appointment updated successfully!");
      navigate("/Dashboardpage");
    } catch (error) {
      console.error("Error updating appointment:", error);
      alert("Failed to update appointment");
    }
  };

  return (
    <div className="editapp_container">
      <form onSubmit={handleSubmit} className="editapp_form">
        <h1 className="editapp_title">Update Appointment</h1>

        <label className="editapp_label">Owner's Name:</label>
        <input
          type="text"
          className="editapp_input"
          value={ownerName}
          onChange={(e) => setOwnerName(e.target.value)}
          required
        />

        <label className="editapp_label">NIC Number:</label>
        <input
          type="text"
          className="editapp_input"
          value={autoGeneratedId}
          onChange={(e) => setAutoGeneratedId(e.target.value)}
          required
        />

        <label className="editapp_label">Service:</label>
        <select
          className="editapp_input"
          value={service}
          onChange={(e) => setService(e.target.value)}
          required
        >
          <option value="">-- Select a service --</option>
          <option value="Veterinary Services">Veterinary Services</option>
          <option value="Pet Grooming">Pet Grooming</option>
          <option value="Vaccinations">Vaccinations</option>
          <option value="Pet Daycare">Pet Daycare</option>
          <option value="Other">Other</option>
        </select>

        <label className="editapp_label">Appointment Date:</label>
        <input
          type="date"
          className="editapp_input"
          value={date}
          onChange={(e) => setDate(e.target.value)}
          required
        />

        <label className="editapp_label">Appointment Time:</label>
        <input
          type="time"
          className="editapp_input"
          value={time}
          onChange={(e) => setTime(e.target.value)}
          required
        />

        <button type="submit" className="editapp_button">
          Update
        </button>
      </form>
    </div>
  );
}

export default UpdateAppointment;
